### ISSUE TITLE
Denied on Google App Engine, creating temp files

### ISSUE THREAD

**Issue by zemanel** [denied/denied#1]
```
Traceback (most recent call last):
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 3185, in _HandleRequest
    self._Dispatch(dispatcher, self.rfile, outfile, env_dict)
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 3128, in _Dispatch
    base_env_dict=env_dict)
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 515, in Dispatch
    base_env_dict=base_env_dict)
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 2387, in Dispatch
    self._module_dict)
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 2297, in ExecuteCGI
    reset_modules = exec_script(handler_path, cgi_path, hook)
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 2193, in ExecuteOrImportScript
    exec module_code in script_module.__dict__
  File "/home/jmoreira/Projectos/HNCareers/trunk/HNCareers/src/HNCareers/main.py", line 4, in <module>
    from deny import *
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 1272, in Decorate
    return func(self, *args, **kwargs)
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 1922, in load_module
    return self.FindAndLoadModule(submodule, fullname, search_path)
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 1272, in Decorate
    return func(self, *args, **kwargs)
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 1824, in FindAndLoadModule
    description)
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 1272, in Decorate
    return func(self, *args, **kwargs)
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/tools/dev_appserver.py", line 1775, in LoadModuleRestricted
    description)
  File "/home/jmoreira/Projectos/HNCareers/trunk/HNCareers/src/HNCareers/deny.py", line 41, in <module>
    _deny()
  File "/home/jmoreira/Projectos/HNCareers/trunk/HNCareers/src/HNCareers/deny.py", line 7, in _deny
    directory = tempfile.mkdtemp(prefix='denied_uframework')
  File "/home/jmoreira/Develop/google_appengine_1.3.2/google/appengine/dist/tempfile.py", line 57, in PlaceHolder
    raise NotImplementedError("Only tempfile.TemporaryFile is available for use")
```

**Comment by mitsuhiko** [comment]
Denied is a joke framework. Use flask instead: http://github.com/mitsuhiko/flask

**Comment by kennethreitz** [comment]
This is awesome.

**Comment by zemanel** [comment]
this framework's very buggy and very lagging on support, as this issue is still open, since 2 years ago :-)

```
echo "sarcasm" > @kennethreitz
```

**Comment by kennethreitz** [comment]
It isn't a bug, it's a feature. It helps us achieve webscale.

**Comment by zemanel** [comment]
@kennethreitz i see! i was particularly fond of the code minification technique :-)
